(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/moment/moment"],{"5d56":function(t,n,e){"use strict";var r=e("c2af"),a=e.n(r);a.a},b607:function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var r=a(e("4795"));function a(t){return t&&t.__esModule?t:{default:t}}function u(t,n,e,r,a,u,o){try{var c=t[u](o),i=c.value}catch(s){return void e(s)}c.done?n(i):Promise.resolve(i).then(r,a)}function o(t){return function(){var n=this,e=arguments;return new Promise((function(r,a){var o=t.apply(n,e);function c(t){u(o,r,a,c,i,"next",t)}function i(t){u(o,r,a,c,i,"throw",t)}c(void 0)}))}}var c={data:function(){return{data:[]}},methods:{setData:function(){return o(r.default.mark((function t(){var n,e,a,u,o,c,i,s;return r.default.wrap((function(t){while(1)switch(t.prev=t.next){case 0:return n=wx.cloud.database({env:"edgar"}),e=20,t.next=4,n.collection("publish").count();case 4:if(a=t.sent,u=a.total,0!==u){t.next=8;break}return t.abrupt("return",new Promise((function(t){t([])})));case 8:for(o=Math.ceil(u/e),c=[],i=0;i<o;i++)s=n.collection("publish").orderBy("date","desc").skip(i*e).limit(e).get(),c.push(s);return t.next=13,Promise.all(c);case 13:return t.abrupt("return",t.sent.reduce((function(t,n){return{data:t.data.concat(n.data),errMsg:t.errMsg}})));case 14:case"end":return t.stop()}}),t)})))()}},mounted:function(){var t=this;wx.showLoading({title:"加载中"}),this.setData().then((function(n){t.data=n.data,wx.hideLoading()}))}};n.default=c},c2af:function(t,n,e){},d663:function(t,n,e){"use strict";var r={momentBase:function(){return Promise.all([e.e("common/vendor"),e.e("components/moment-base/moment-base")]).then(e.bind(null,"4e5d"))}},a=function(){var t=this,n=t.$createElement;t._self._c},u=[];e.d(n,"b",(function(){return a})),e.d(n,"c",(function(){return u})),e.d(n,"a",(function(){return r}))},e402:function(t,n,e){"use strict";e.r(n);var r=e("d663"),a=e("fadf");for(var u in a)"default"!==u&&function(t){e.d(n,t,(function(){return a[t]}))}(u);e("5d56");var o,c=e("f0c5"),i=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"89d529ca",null,!1,r["a"],o);n["default"]=i.exports},fadf:function(t,n,e){"use strict";e.r(n);var r=e("b607"),a=e.n(r);for(var u in r)"default"!==u&&function(t){e.d(n,t,(function(){return r[t]}))}(u);n["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/moment/moment-create-component',
    {
        'components/moment/moment-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e402"))
        })
    },
    [['components/moment/moment-create-component']]
]);
