(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/avatar/avatar"],{"13d1":function(t,e,n){"use strict";var o=n("baca"),r=n.n(o);r.a},2143:function(t,e,n){"use strict";n.r(e);var o=n("b4dd"),r=n("360d");for(var u in r)"default"!==u&&function(t){n.d(e,t,(function(){return r[t]}))}(u);n("13d1");var c,s=n("f0c5"),i=Object(s["a"])(r["default"],o["b"],o["c"],!1,null,"7d838024",null,!1,o["a"],c);e["default"]=i.exports},"360d":function(t,e,n){"use strict";n.r(e);var o=n("6743"),r=n.n(o);for(var u in o)"default"!==u&&function(t){n.d(e,t,(function(){return o[t]}))}(u);e["default"]=r.a},6743:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o=n("2f62");function r(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(t);e&&(o=o.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.push.apply(n,o)}return n}function u(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?r(Object(n),!0).forEach((function(e){c(t,e,n[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))}))}return t}function c(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var s={data:function(){return{}},computed:u({},(0,o.mapState)(["isLogin","userInfo"])),methods:u({getUserInfo:function(){var e=this;t.getUserInfo({success:function(n){e.$refs.toast.show({title:"登录成功",type:"success"});var o=n;wx.cloud.callFunction({name:"getOpenId",success:function(n){t.setStorageSync("user",o.userInfo),e.setIsLogin(!0),e.setUserInfo(o.userInfo),e.setOpenId(n.result.OPENID)},fail:function(t){console.log(t),e.$refs.toast.show({title:"获取id失败",type:"error"})}})},fail:function(t){console.log(t)}})}},(0,o.mapMutations)(["setIsLogin","setUserInfo","setOpenId"])),mounted:function(){var e=this;this.isLogin||t.checkSession({success:function(){var n=t.getStorageSync("user");e.setIsLogin(!0),e.setUserInfo(n)},fail:function(){console.log("false"),e.setIsLogin(!1)}})}};e.default=s}).call(this,n("543d")["default"])},b4dd:function(t,e,n){"use strict";var o={uRow:function(){return n.e("uview-ui/components/u-row/u-row").then(n.bind(null,"7d41"))},uCol:function(){return n.e("uview-ui/components/u-col/u-col").then(n.bind(null,"8fa9"))},uAvatar:function(){return n.e("uview-ui/components/u-avatar/u-avatar").then(n.bind(null,"0691"))},uToast:function(){return n.e("uview-ui/components/u-toast/u-toast").then(n.bind(null,"12e7"))}},r=function(){var t=this,e=t.$createElement;t._self._c},u=[];n.d(e,"b",(function(){return r})),n.d(e,"c",(function(){return u})),n.d(e,"a",(function(){return o}))},baca:function(t,e,n){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/avatar/avatar-create-component',
    {
        'components/avatar/avatar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2143"))
        })
    },
    [['components/avatar/avatar-create-component']]
]);
