(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/publish/publish"],{"0fcb":function(t,n,e){"use strict";e.r(n);var o=e("1112"),u=e("6d3a");for(var i in u)"default"!==i&&function(t){e.d(n,t,(function(){return u[t]}))}(i);e("8204");var r,c=e("f0c5"),a=Object(c["a"])(u["default"],o["b"],o["c"],!1,null,"72dc3623",null,!1,o["a"],r);n["default"]=a.exports},1112:function(t,n,e){"use strict";var o={uTopTips:function(){return e.e("uview-ui/components/u-top-tips/u-top-tips").then(e.bind(null,"e8af"))},uGap:function(){return e.e("uview-ui/components/u-gap/u-gap").then(e.bind(null,"83e5"))},uButton:function(){return e.e("uview-ui/components/u-button/u-button").then(e.bind(null,"af9b"))},uModal:function(){return e.e("uview-ui/components/u-modal/u-modal").then(e.bind(null,"2c34"))}},u=function(){var t=this,n=t.$createElement;t._self._c},i=[];e.d(n,"b",(function(){return u})),e.d(n,"c",(function(){return i})),e.d(n,"a",(function(){return o}))},"5b01":function(t,n,e){},"6d3a":function(t,n,e){"use strict";e.r(n);var o=e("d0b2"),u=e.n(o);for(var i in o)"default"!==i&&function(t){e.d(n,t,(function(){return o[t]}))}(i);n["default"]=u.a},8204:function(t,n,e){"use strict";var o=e("5b01"),u=e.n(o);u.a},d0b2:function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=e("2f62");function u(t,n){var e=Object.keys(t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(t);n&&(o=o.filter((function(n){return Object.getOwnPropertyDescriptor(t,n).enumerable}))),e.push.apply(e,o)}return e}function i(t){for(var n=1;n<arguments.length;n++){var e=null!=arguments[n]?arguments[n]:{};n%2?u(Object(e),!0).forEach((function(n){r(t,n,e[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(e)):u(Object(e)).forEach((function(n){Object.defineProperty(t,n,Object.getOwnPropertyDescriptor(e,n))}))}return t}function r(t,n,e){return n in t?Object.defineProperty(t,n,{value:e,enumerable:!0,configurable:!0,writable:!0}):t[n]=e,t}var c={data:function(){return{content:"",show:!1,info:"请先登录"}},methods:{bindInput:function(t){console.log(t)},submit:function(){var t=this;if(""!==this.content){var n=wx.cloud.database({env:"edgar"});console.log(this.OpenId),n.collection("publish").add({data:{content:this.content,date:new Date,nickname:this.userInfo.nickName,avatarUrl:this.userInfo.avatarUrl}}).then((function(){t.content="",t.$emit("jump",0),wx.showToast({title:"发布成功"})}))}else this.$refs.uTips.show({title:"内容不能为空",type:"error"})},confirm:function(){t.switchTab({url:"/pages/mine/mine"})}},mounted:function(){console.log("publish mount"),console.log(this.isLogin),this.show=!this.isLogin},computed:i({},(0,o.mapState)(["OpenId","isLogin","userInfo"]))};n.default=c}).call(this,e("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/publish/publish-create-component',
    {
        'components/publish/publish-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("0fcb"))
        })
    },
    [['components/publish/publish-create-component']]
]);
