(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/notice/notice"],{"0c73":function(t,n,e){"use strict";var u={uSection:function(){return e.e("uview-ui/components/u-section/u-section").then(e.bind(null,"38cc"))},uGap:function(){return e.e("uview-ui/components/u-gap/u-gap").then(e.bind(null,"83e5"))},uCellGroup:function(){return e.e("uview-ui/components/u-cell-group/u-cell-group").then(e.bind(null,"0377"))},uCellItem:function(){return e.e("uview-ui/components/u-cell-item/u-cell-item").then(e.bind(null,"023c"))},uToast:function(){return e.e("uview-ui/components/u-toast/u-toast").then(e.bind(null,"12e7"))}},o=function(){var t=this,n=t.$createElement,e=(t._self._c,t.__map(t.data,(function(n,e){var u=t._f("dateFormat")(n.date);return{$orig:t.__get_orig(n),f0:u}})));t.$mp.data=Object.assign({},{$root:{l0:e}})},i=[];e.d(n,"b",(function(){return o})),e.d(n,"c",(function(){return i})),e.d(n,"a",(function(){return u}))},cc52:function(t,n,e){"use strict";e.r(n);var u=e("cf65"),o=e.n(u);for(var i in u)"default"!==i&&function(t){e.d(n,t,(function(){return u[t]}))}(i);n["default"]=o.a},cf65:function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e={data:function(){return{data:[],show:!1}},filters:{dateFormat:function(t){return[t.getFullYear(),t.getMonth()+1,t.getDate()].join("-")}},methods:{getMore:function(){this.$refs.uToast.show({title:"加载更多内容，敬请期待"})},setData:function(){var t=this;wx.showLoading({title:"加载中"});var n=wx.cloud.database({env:"edgar"}),e=5;return new Promise((function(u,o){n.collection("notice").orderBy("date","desc").limit(e).get().then((function(n){t.data=n.data,t.show=!0,u(n)})).catch((function(n){o(n),t.$refs.uToast.show({title:"请求数据失败",type:"error"})}))}))},refresh:function(){this.setData().then((function(){wx.hideLoading(),t.stopPullDownRefresh()}))}},mounted:function(){this.setData().then((function(){wx.hideLoading()}))}};n.default=e}).call(this,e("543d")["default"])},d1b6:function(t,n,e){},f35c:function(t,n,e){"use strict";e.r(n);var u=e("0c73"),o=e("cc52");for(var i in o)"default"!==i&&function(t){e.d(n,t,(function(){return o[t]}))}(i);e("f963");var c,a=e("f0c5"),r=Object(a["a"])(o["default"],u["b"],u["c"],!1,null,null,null,!1,u["a"],c);n["default"]=r.exports},f963:function(t,n,e){"use strict";var u=e("d1b6"),o=e.n(u);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/notice/notice-create-component',
    {
        'components/notice/notice-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("f35c"))
        })
    },
    [['components/notice/notice-create-component']]
]);
